server:
  port: 3333
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fenbu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
#  jackson:
#    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mybatis-mapper/*Mapper.xml

logging:
  level:
    com.baidu: debug
